language: node_js
node_js: lts/*

branches:
  only: PROD

install:
  - npm install -g firebase-tools

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then if [ $(wget -O /dev/null https://pawelbana.ch 2>&1 | grep -f HTTP | cut -d ' ' -f 6) == 201 ]; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then rm -rf public/* && wget -r -np -nH -P public/ https://ch-pawelbana-staging.firebaseapp.com && firebase deploy -P PROD --token $FIREBASE_TOKEN; fi'

env:
  global:
    secure: DJfGXUDo/Swl87mN2j5wbLKEIKfDGV5b3Ikjq4abivTj3I8/pzTC28PLCAcDHT4rkSXAcLCNW8qdhHLJQIxtIqQlZFwl8Rdr0f6KjzqaA6Op2SswPWwfIJtYjCNLtzbMNZz9vZcgIxuU+fBIxUAa38Ha4AzDDdwXPUy24boKSOe9U21bunl5Bf6EeS+yJVY10ajJThtB8YxLc1pEN+/FwTbJ0fI581RFjv5fpBx63m3BsQTEmWEiFiejkGg0+g5dYuxC8Xq0zF4ZHhjfLMGUsTFn/2vbX8GSl9yBWeSApYncx5l+fHaL5aDqTN6jM8R1MVg9wgMZddwETadiJ6BuhheZLxGOPl4pUzY96uMA33ASnhxm5r0N7I+sZ4V+aF+VrP0VxpLV7PgLfqd2mBG1RFRLC/ZX2tuNy9XjLTK72QBD1YQ9gk29DdPmaqtV/aXwWGgN+ahCsvOhbZi/FIBj6o/M0t52b8gokChjYXWgFbUxUxc5XNWV+fN39NilCu0C0FzQ0YRn2HH672U1fPbWXHb3bcVfS6xs5WlULWMgkOXDbGsJXje5xb9V83oD6VsPUbPDOS8criolYTjeIvb5xr5fiA3huAoBdxkT4TZ/0soIgTi6qk6F3SgnLa1zSkNpXBnujw0MtBo2siraYacAfOFigMsPhI+VK9/8jzNLNnU=
