---
language: go
go: master

branches:
  only: STAGING

install:
  - curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep browser_download_url | grep hugo | grep -v hugo_extended | grep Linux-64bit.tar.gz | cut -d '"' -f 4
  - sudo tar -zxf $(ls *Linux-64bit.tar.gz) -C /usr/local/bin hugo
  - npm install -g firebase-tools

script: rm -rf public/* && hugo && firebase deploy -P STAGING --token $FIREBASE_TOKEN

env:
  global:
    secure: DJfGXUDo/Swl87mN2j5wbLKEIKfDGV5b3Ikjq4abivTj3I8/pzTC28PLCAcDHT4rkSXAcLCNW8qdhHLJQIxtIqQlZFwl8Rdr0f6KjzqaA6Op2SswPWwfIJtYjCNLtzbMNZz9vZcgIxuU+fBIxUAa38Ha4AzDDdwXPUy24boKSOe9U21bunl5Bf6EeS+yJVY10ajJThtB8YxLc1pEN+/FwTbJ0fI581RFjv5fpBx63m3BsQTEmWEiFiejkGg0+g5dYuxC8Xq0zF4ZHhjfLMGUsTFn/2vbX8GSl9yBWeSApYncx5l+fHaL5aDqTN6jM8R1MVg9wgMZddwETadiJ6BuhheZLxGOPl4pUzY96uMA33ASnhxm5r0N7I+sZ4V+aF+VrP0VxpLV7PgLfqd2mBG1RFRLC/ZX2tuNy9XjLTK72QBD1YQ9gk29DdPmaqtV/aXwWGgN+ahCsvOhbZi/FIBj6o/M0t52b8gokChjYXWgFbUxUxc5XNWV+fN39NilCu0C0FzQ0YRn2HH672U1fPbWXHb3bcVfS6xs5WlULWMgkOXDbGsJXje5xb9V83oD6VsPUbPDOS8criolYTjeIvb5xr5fiA3huAoBdxkT4TZ/0soIgTi6qk6F3SgnLa1zSkNpXBnujw0MtBo2siraYacAfOFigMsPhI+VK9/8jzNLNnU=
