---
language: go
go: master

branches:
  only: STAGING

install:
  - curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep browser_download_url | grep hugo | grep -v hugo_extended | grep Linux-64bit.tar.gz | cut -d '"' -f 4 | wget -qi -
  - sudo tar -zxf $(ls *Linux-64bit.tar.gz) -C /usr/local/bin hugo
  - npm install -g firebase-tools

script: rm -rf public/* && hugo && firebase deploy -P STAGING --token $FIREBASE_TOKEN

env:
  global:
  secure: bEeV6YcwIu+PJwI7fQuzYGMKKkpfZMd9QJ3Za06UjKLTVrPZmjCB/NfX9eBjQAaqOCpnVNcyt182wTOun0XAWXTQXsxMBT83XdSLhJG3QG5ga86lvo8Dg4hNQIoyZpFVerbI70bdRxXAc4asLJmD4OTDeewGmBsX+ZZTfWhS12QWqMMW/PFA8SPGu5M+q1OtjzEY2eBk7MDT7i0e4MA6r2M2luZI9Uwzpt9pl5tsUBtwX1k8fDyIbv24cRBFGLWu05lui9ZqFvK2fa2VOxepDBRoOD1joiLUYewV2a7has54rh7404VgSwx34tR4k55fxDYirRFBLl0rW3EMCVae26musI/LuXjxBCA4POQhK3UPnIuYoGeJurPR8yz0DOmMOWzc1q5pe7vhz3B5KcQxvRbrRZM6pFCGsGhiH3mkISbDfndKBzHqeIizEGiJr2cEiPG38yhrNKxZjVUf6U1Il3s/78YpJ73DRQp6KwFhujk6dZLW6PYk91/ZJgKMl5/4kJgbklD2qTLNzPYPrWwNvSLtaqBC8kPNvXE+nFxuF7k73HOanXMVS+v/zJEgWpa65S8j3k73YYDA8k7mxWMa0HunrLjlU1DdS6AzPzTN7YgmpxliTn1I+xGRYgPrtsNortQLfzFz5TAgfw/4KwRN6FR7H4K209xehwZT4UG0Ds8=
