language: go
go: 1.8.x

dist: trusty

branches:
  only: PROD

install:
  - npm install -g firebase-tools

before_script:
  - rm -rf public/*
  - wget -r -np -nH -P public/ https://ch-pawelbana-staging.firebaseapp.com

script: firebase deploy -P PROD --token $FIREBASE_TOKEN

env:
  global:
    secure: DJfGXUDo/Swl87mN2j5wbLKEIKfDGV5b3Ikjq4abivTj3I8/pzTC28PLCAcDHT4rkSXAcLCNW8qdhHLJQIxtIqQlZFwl8Rdr0f6KjzqaA6Op2SswPWwfIJtYjCNLtzbMNZz9vZcgIxuU+fBIxUAa38Ha4AzDDdwXPUy24boKSOe9U21bunl5Bf6EeS+yJVY10ajJThtB8YxLc1pEN+/FwTbJ0fI581RFjv5fpBx63m3BsQTEmWEiFiejkGg0+g5dYuxC8Xq0zF4ZHhjfLMGUsTFn/2vbX8GSl9yBWeSApYncx5l+fHaL5aDqTN6jM8R1MVg9wgMZddwETadiJ6BuhheZLxGOPl4pUzY96uMA33ASnhxm5r0N7I+sZ4V+aF+VrP0VxpLV7PgLfqd2mBG1RFRLC/ZX2tuNy9XjLTK72QBD1YQ9gk29DdPmaqtV/aXwWGgN+ahCsvOhbZi/FIBj6o/M0t52b8gokChjYXWgFbUxUxc5XNWV+fN39NilCu0C0FzQ0YRn2HH672U1fPbWXHb3bcVfS6xs5WlULWMgkOXDbGsJXje5xb9V83oD6VsPUbPDOS8criolYTjeIvb5xr5fiA3huAoBdxkT4TZ/0soIgTi6qk6F3SgnLa1zSkNpXBnujw0MtBo2siraYacAfOFigMsPhI+VK9/8jzNLNnU=
