---
language: node_js
node_js: lts/*

git:
  depth: false

branches:
  only: PROD

script:
  - if [ $TRAVIS_EVENT_TYPE = "pull_request" ]; then
      $([ $(wget -O /dev/null https://staging.pawelbana.ch 2>&1 | grep -F HTTP | cut -d ' ' -f 6) = 200 ]) || travis_terminate 1;
    else
      npm install -g firebase-tools || travis_terminate 1;
      rm -rf public/* || travis_terminate 1;
      wget -r -np -nH -P public/ https://ch-pawelbana-staging.firebaseapp.com || travis_terminate 1;
      firebase deploy -P PROD --token $FIREBASE_TOKEN || travis_terminate 1;
    fi

env:
  global:
  - secure: j4CfBlB+T0VwOiBMyPF+It09FV/4uLwuxQFWsrwAoF/qQo5VsjidYiOTdG7iEiIJMWUZhBZ4nhb9P9yfp1rNi4k9RFWsHKHCmxfDqnTOD07mZOB5tegUsykDmUxoJragRMQ6rRRu5Uy1foTkxi9DkXbNEW1B6v7UCh44CMnViTKwncx5mOT7shIHBzbENcj2KDcZf1W3IlLBtDr4mOoN25X5hKBudMF8iFCI/BfZbWePalh5J2cCsup2Y+tNO6vLU0XmEY84XCLUuPAVvTmqIq9z6BHvo+ahcfGIz4F7bqB2QOhJytYYsigHSz3mH1VMyd0DmoqI+2z280Qsc3nHd81GJaeeJf1ze91Pd38roPnDbtWfxrLB7dSKb+MWsnktZbp3BzX7UJWE97IF6Iu1STxzmMUk1e1L36cPWvO3nJG8vOByeN2YMYRguRypuPz6B26/fi4Aq9Ip0v7Bvry1oESzewEYLG8tzFOVeaAfSby3F5fjy/WGSsUpvrwMYUAfvmp7H0UsneUnct/ZCq9uhKReGXBWO1qKJh3ZXcAIzkuekknGQ4VPWhgnf7Us/EYlun6vaAGvYXW+hCIPsyLEWcGo4e7iZndniemWlp4hR28MTpS79WT92V+xe1ATg4+kphl8wo/doW2Wg2LOuxxjupgvl94Jz53SDosfRe+bsWs=
