name: CI of the prod branch

env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone code repository
        run: | 
          git clone https://github.com/${{ github.repository }} .
          git checkout ${{ github.sha }}
      
      - name: Check staging.pawelbana.ch for HTTP status code 200
        run: $([ $(wget -O /dev/null https://staging.pawelbana.ch 2>&1 | grep -F HTTP | cut -d ' ' -f 6) = 200 ]) || exit 1;

      - name: Download content of public directory from staging.pawelbana.ch
        run: |
          rm -rf public/*
          wget -r -np -nH -P public/ https://ch-pawelbana-staging-eur3.firebaseapp.com;

      - name: Download Firebase
        run: |
          curl -Lo ./firebase_bin https://firebase.tools/bin/linux/latest
          chmod u+x firebase_bin

      - name: Deploy to Firebase
        run: ./firebase_bin deploy -P prod --token $FIREBASE_TOKEN