name: CI

on:
  push:
    branches: [ STAGING ]
  pull_request:
    branches: [ STAGING ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run a multi-line script
      run: |
        curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep browser_download_url | grep hugo | grep -v hugo_extended | grep Linux-64bit.tar.gz | cut -d '"' -f 4 | wget -qi -
        curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep browser_download_url | grep hugo | grep _checksums.txt | cut -d '"' -f 4 | wget -qi -
        hugoGzip=$(ls -t *Linux-64bit.tar.gz | head -1)
        checksumFile=$(ls -t *_checksums.txt | head -1)
        grep $(sha256sum $hugoGzip | awk '{print $1}') $checksumFile
        sudo tar -zxf $hugoGzip -C /usr/local/bin hugo
      
    - name: Install firebase
        npm install -g firebase-tools
