name: CI of the staging branch

env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone code repository
        run: | 
          git clone --depth=1 https://github.com/${{ github.repository }} .
          git checkout ${{ github.sha }}

      - name: Download Hugo
        run: |
          curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep browser_download_url | grep hugo | grep -v hugo_extended | grep Linux-32bit.tar.gz | cut -d '"' -f 4 | wget -qi -
          curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep browser_download_url | grep hugo | grep _checksums.txt | cut -d '"' -f 4 | wget -qi -
          hugoGzip=$(ls -t *Linux-32bit.tar.gz | head -1)
          checksumFile=$(ls -t *_checksums.txt | head -1)
          grep $(sha256sum $hugoGzip | awk '{print $1}') $checksumFile
          sudo tar -zxf $hugoGzip -C /usr/local/bin hugo

      - name: Download Firebase
        run: |
          curl -Lo ./firebase_bin https://firebase.tools/bin/linux/latest
          chmod u+x firebase_bin

      - name: Hugo builds your site
        run: | 
          rm -rf public/*
          hugo

      - name: Deploy to Firebase
        run: ./firebase_bin deploy --only hosting -P staging --token $FIREBASE_TOKEN
